name: CI
on: [push, pull_request]
jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-12]
        xcode: [13.2.1, 13.3.1]
        exclude:
          - os: macos-10.15
            xcode: 13.2.1
          - os: macos-10.15
            xcode: 13.3.1
          - os: macos-11
            xcode: 13.3.1
          - os: macos-12
            xcode: 12.4
    env:
      DEVELOPER_DIR: "/Applications/Xcode_${{ matrix.xcode }}.app/Contents/Developer"
    steps:
    - uses: actions/checkout@v2
    - name: Build and Test
      run: |
        sed -i '' 's/.macOS\(.*\)/.macOS("10.9")/g' Package*.swift
        swift test
